### ISSUE TITLE
Prefer `Thread.join(timeout)`.

### ISSUE THREAD

**Issue by ioquatix** [aerospike/aerospike-client-ruby#103]
https://github.com/aerospike/aerospike-client-ruby/blob/8488c41607dc4738978827bc3f491d85dfcca200/lib/aerospike/cluster.rb#L433-L454

**Comment by ioquatix** [comment]
Also this code does not look particularly thread safe.

**Comment by khaf** [comment]
Thanks for your feedback. We invite and encourage PRs.

**Comment by MarcPer** [comment]
I've opened a PR to address this issue.

**Comment by khaf** [comment]
Thank you, I have already merged it; will release a new version before the weekend.

**Comment by mensfeld** [comment]
@khaf ping ^^

**Comment by khaf** [comment]
Released yesterday. I'm going to go ahead and close this ticket. Feel free to reopen, or issue new ones.

**Comment by mensfeld** [comment]
@khaf :pray: @madejejej can we bump it, please?

**Comment by khaf** [comment]
Now that I have your attention, does anyone use Crystal? Any feedback, opinions?

**Comment by ioquatix** [comment]
Most of the things that Crystal does in syntax (in terms of static typing) can be done at runtime by a sufficiently good JIT compiler. Node.js already showed that you can get close to the performance of C with runtime instrumentation and feedback into the JIT, and in some cases it appears you would be able to do better than C if your runtime analysis reveals insights that can't be known at compile time.

**Comment by khaf** [comment]
Thanks @ioquatix . But such runtime does not exist for Ruby and last I checked, even JRuby was not a drop-in replacement for CRuby (and the GIL is still there). It's surprising to me that the Rubyists are not interested in Crystal. It's almost a dream come true.

**Comment by ioquatix** [comment]
TruffleRuby is pretty close.

**Comment by MarcPer** [comment]
> This is a great talk on the subject: https://www.youtube.com/watch?v=r-TLSBdHe1A - it's not specific to Crystal but I think it helps frame "performance" a bit more objectively which is necessary if you consider syntax/performance trade-offs.

Indeed a great talk. Thanks for sharing.
