### ISSUE TITLE
Aerospike 1.0: bcrypt missing from gem dependencies

### ISSUE THREAD

**Issue by rvmiller** [aerospike/aerospike-client-ruby#11]
Installing atomic 1.1.99 (was 1.1.16)
Installing msgpack 0.5.10 (was 0.5.9)
Installing aerospike 1.0.0 (was 0.1.6)
...
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from atomic:
This gem has been deprecated and merged into Concurrent Ruby (http://concurrent-ruby.com).
Post-install message from aerospike:
Thank you for using Aerospike!
You can report issues on github.com/aerospike/aerospike-client-ruby
rmiller:~/ws/automated-tests (master *=)$ pry
[1] pry(main)>
[2] pry(main)>
[3] pry(main)> require 'aerospike'
LoadError: cannot load such file -- bcrypt
from /Users/rmiller/.rvm/gems/ruby-1.9.3-p545/gems/aerospike-1.0.0/lib/aerospike.rb:8:in `require'
[4] pry(main)>

For reference, line 8 in aerospike.rb is, as you would expect:
require 'bcrypt'

I use bundler. I was able to fix this by removing all aerospike gems, deleting my Gemfile.lock, and explicitly adding bcrypt to my Gemfile, then doing a bundle install.  

The bcrypt gem (version 3.1.9) should be added as a dependency to the aerospike gem.

Thanks!

**Comment by khaf** [comment]
Argh, that's embarrassing. 

Thanks for letting me know, gem is updated.

Don't hesitate to let me know about your experience with the library.

**Comment by rvmiller** [comment]
Hey no worries, glad to help!  Otherwise, this gem has been excellent! I love the interaction pattern, very intuitive, and reliable. We use it in our test acceptance test libraries, as well as some internal monitoring apps we have.

If I have any specific feedback or requests, I'll make sure to let you know. Thanks again for the quick turnaround!
