### ISSUE TITLE
100% CPU and infinity loop when we can't connect to one of nodes

### ISSUE THREAD

**Issue by prepor** [aerospike/aerospike-client-ruby#14]
Hello!

Ruby Aerospike Client does nonblock connect but doesn't wait for completion. And doesn't check connection status later.

So, after https://github.com/aerospike/aerospike-client-ruby/blob/master/lib/aerospike/cluster/node_validator.rb#L65 it goes into infinity loop in https://github.com/aerospike/aerospike-client-ruby/blob/master/lib/aerospike/cluster/connection.rb#L55. And our production is down after deploy :)

**Comment by khaf** [comment]
Fixed and Released. Thanks for your report and PR.
