### ISSUE TITLE
random key fail : ResultCode 20 unknown in the client

### ISSUE THREAD

**Issue by JokerCatz** [aerospike/aerospike-client-ruby#18]
just code

    require 'aerospike'
    include Aerospike
    client = Client.new("127.0.0.1", 3000)
    t = Time.now.to_f ; 500.times do key = Key.new('tempi', rand.to_s, rand.to_s) ; client.put(key, {'wer' => rand.to_s}) ; client.get(key).bins ; end ; Time.now.to_f - t
    #=> Aerospike::Exceptions::Aerospike: ResultCode 20 unknown in the client. Please file a github issue.

**Comment by ook** [comment]
ResultCode 20 is "invalid namespace". So "tempi" is not declared into your aerospike client.

Too many basic resultCode are missing in aerospike ruby client…

**Comment by JokerCatz** [comment]
okay , I change to

    key = Key.new('test', 'test', rand.to_s) ; client.put(key, {'test' => rand.to_s})

it's work and fast :) , but Aerospike::Client & Aerospike::Record are TOO MANY useless details...

    client.inspect.length #=> 10621449
    client.get(key).inspect.length #=> 338291

& I use ruby 2.1.5p273

**Comment by khaf** [comment]
@JokerCatz Aerospike client is much more than a simple database driver and abstracts out the complexity of working with a distributing system. It keeps references to a lot of internal objects, which are fairly large.

`Aerospike::Record` keeps a *reference* to the node the record was received from, but it seems `.inspect.length` is counting the size of that reference in its result.

**Comment by JokerCatz** [comment]
did you try the README demo code in irb & ssh ?
irb will puts inspect string ,  it useless & it too long not useful for debug

in Ruby irb will show object.inspect each line exec , for example , if i enter

    irb> client

will be

    irb> puts client.inspect
    #client.inspect = string & string.length = 10621449

you can try to fix it for

    class Aerospike::Record
      def inspect
        return "something important message" # like count / status / signature ......
      end
    end

((& sorry my poor English...

**Comment by jhecking** [comment]
The original issue about "Aerospike::Exceptions::Aerospike: ResultCode 20 unknown in the client." has been fixed in #19, so closing this.
