### ISSUE TITLE
Console and logs polluted by « Tend finished » log

### ISSUE THREAD

**Issue by ook** [aerospike/aerospike-client-ruby#20]
lib/aerospike/cluster/cluster.rb:241:      Aerospike.logger.info("Tend finished. Live node count: #{nodes.length}")

This line pollute console and logs after a first aerospike command. Spaming so fast a console is useless after the very first as command.

Since it's no use for simple as user, it should be a conditional log, disabled by default.

**Comment by khaf** [comment]
Why aren't you setting your log level to WARN or ERROR?

Tend is Info level to show you exactly when the cluster was partitioned and a node was dropped.

**Comment by ook** [comment]
Because I'm debugging :)

As you say, it's cluster/node stuff, not client concerns. In a certain point of view, the client user should just be able to "ignore" he's discussing with an AS node and forget about it.

**Comment by khaf** [comment]
bah, and here I was thinking maybe I should make it a debug log! :)

For the moment the easiest solution is to comment it. 

Any suggestions regarding how to improve the situation?

**Comment by ook** [comment]
Two approaches:

# Create a logger overlay and tag the entries along concern (client/node/etc.) and let user configure this overlay to trash certain tags 
# At each logging class level, let configure a guard condition to log or not

**Comment by Angelmmiguel** [comment]
What do you think about create a configuration param in initializers to disable this log (enabled by default)?

**Comment by ook** [comment]
Sound interesting to me ears.

**Comment by Angelmmiguel** [comment]
For example, I created a Gem and set a [compatibility](https://github.com/Angelmmiguel/material_icons#compatibility) param config in initializer. What do you think @khaf?

**Comment by khaf** [comment]
I'm not against it. Anybody wants to take a stab at it?

**Comment by Angelmmiguel** [comment]
ok! I think I have some time this week and I'm working with Aerospike, so I will create a PL

**Comment by jhecking** [comment]
With 04a23a090eaa48d7f4eddc0ace0712c8564544c8 the tend info message only gets logged if any nodes were added to or removed from the cluster.
