### ISSUE TITLE
AS Client connection should timeout by default

### ISSUE THREAD

**Issue by ook** [aerospike/aerospike-client-ruby#21]
AS Client connection appears to have no timeout right now. For unknown reason, I sometimes have connection stall and the AS connection stay stall forever until a SIGTERM. AS Client connection should timeout by default to 10s (since AS goal is to be fast).

**Comment by khaf** [comment]
All API accept a type of policy, and there you can set timeouts. The default is no timeout.

**Comment by ook** [comment]
Ok, I buy it. Thanks.

**Comment by khaf** [comment]
Just to clarify: Timeout (specially for non-blocking connections) has a small but noticeable impact on performance. The default no Timeout is there for people with reliable and high performing networks.
