### ISSUE TITLE
Cache queries

### ISSUE THREAD

**Issue by Angelmmiguel** [aerospike/aerospike-client-ruby#25]
Hello!

We are working with Aerospike on our application and we have the following situation:
* Low rate of writing
* A lot of read queries

I'm developing a cache for queries on our Rails environment (outside the gem), but I need an unique identifier for every query. I think to base identifier on namespace, set, bins and filters.

What do you think about it?

**Comment by khaf** [comment]
Hi, why do you need statements for a cache?

**Comment by Angelmmiguel** [comment]
Because I need to identify a query to assign it the result given from Aerospike

**Comment by khaf** [comment]
Statements are used for queries on Aerospike. A cache normally only needs single key read/writes. Why do you use Queries on Aerospike's side?

**Comment by Angelmmiguel** [comment]
Because we often return a group of key/values based on some filters

**Comment by khaf** [comment]
Why not make a new unique key out of those, and put all those results in an array, in the same record.

It will be fast and scalable. You can also put a TTL on the record to invalidate over time.

**Comment by Angelmmiguel** [comment]
> Why not make a new unique key out of those, and put all those results in an array, in the same record.
So for example, can I make a key on Aerospike to return key/values of a namespace.set with a column greater than an integer?

> You can also put a TTL on the record to invalidate over time.
But will this invalidate a unique Record? If 50 persons access to the same url that need to perform an Aerospike query each one will instance a new Record

Thanks for your responses!

**Comment by khaf** [comment]
> So for example, can I make a key on Aerospike to return key/values of a namespace.set with a column greater than an integer?

You put all the results of that query in one record in Aerospike. That's the traditional idea of caching as far as I understand.

> But will this invalidate a unique Record? If 50 persons access to the same url that need to perform an Aerospike query each one will instance a new Record

It will invalidate it after TTL expires. Can be 24h, can be a week. If the data never expires, or you update it on writes, then no TTL is needed.

**Comment by Angelmmiguel** [comment]
Ok! I understand you. Thanks for your help :)

**Comment by khaf** [comment]
No problem. Don't hesitate to reach out again :)

**Comment by Angelmmiguel** [comment]
Thanks! :smile:
