### ISSUE TITLE
Large string in Aerospike

### ISSUE THREAD

**Issue by Angelmmiguel** [aerospike/aerospike-client-ruby#32]
Hello,

I'm working on an application that needs to store an array of file paths. We are using Aerospike to store this array as JSON string. The problem is the limit of string length that truncates the JSON array string.

To solve this, we think in [Aerospike Large Data Types (LDTs)](http://www.aerospike.com/docs/client/ruby/usage/ldt/ldt.html). Today I update the gem with the last version and start to investigate with them.

The list of methods from [LargeList](https://github.com/aerospike/aerospike-client-ruby/blob/master/lib/aerospike/ldt/large_list.rb) and [Large](https://github.com/aerospike/aerospike-client-ruby/blob/master/lib/aerospike/ldt/large.rb) classes make me think the purpose of this type of data is to check the existence of elements in the list. For example, there isn't any `each` method. I need to access `conf['CompactList']` to get the array.

Do I select the correct data type to solve my problem? If this LDTs is the correct type, what do you think about a pull request with `each` method?

Thanks!

**Comment by jhecking** [comment]
Hi @Angelmmiguel,

Depending on how large the lists are that you need to store, you can use the native [list data type](http://www.aerospike.com/docs/guide/cdt-list.html). [1] The size of the list would only be constrained by the max. record size (up to 1MB for flash backed storage). Would that be sufficient for your use case?

Here is a quick example:

````ruby
client = Aerospike::Client.new('192.168.33.10', 3000)
key = Aerospike::Key.new('test', 'test', 'list')
list = Array.new(10_000){|idx| "/path/to/file/#{idx}"}
client.put(key, "listbin" => list)
record = client.get(key, ["listbin"])
puts record.bins
````

[1] Please note that the Ruby client does not yet implement the list operations. So to modify the list value, you would first have to fetch it from the DB, update it in the client and then write it back.

**Comment by Angelmmiguel** [comment]
Hello @jhecking,

Yes, I think 1MB is enough. We will implement our solution with list data type.

Thanks for your response.

**Comment by jhecking** [comment]
Great! Thanks for the feedback. Feel free to open another issue if you have further questions or visit our community forums at [discuss.aerospike.com](https://discuss.aerospike.com/c/client-libraries/ruby-client).
