### ISSUE TITLE
when use japanese or chinese in bin value get  error: incompatible character encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by fs-wu** [aerospike/aerospike-client-ruby#33]
When I set japanese in bin value, I got such kind error:
" incompatible character encodings: ASCII-8BIT and UTF-8"
How can I avoid that?

Here my easy code:
```
# -*- coding: utf-8 -*-
require 'rubygems'
require 'aerospike'
include Aerospike

client = Client.new('127.0.0.1', 3000)
key = Key.new('test', 'test', 'key1')
bin1 = Bin.new('bin1','あああ')

client.put(key,[bin1])

client.close
```

**Comment by jhecking** [comment]
@fs-wu, thanks for reporting this issue. The Aerospike server stores strings as [binary strings](http://www.aerospike.com/docs/guide/data-types.html), i.e. not bound to any specific encoding. But the Ruby client should assume UTF-8 as the default encoding and convert all string to/from binary encoding automatically.

I have committed a fix to master in 6ef31a86f2663801130fcb74225fca4a09ba6584. I am planning to do a minor bug fix release for the `aerospike` package next week. But if you want, you can build the package yourself from `master` branch and give it a try.

**Comment by fs-wu** [comment]
Thank you,it worked.Wait for your new gem version.

**Comment by jhecking** [comment]
@fs-wu, v1.0.12 of the gem is now available on rubygems.org.
