### ISSUE TITLE
Add node failed: wrong number of arguments

### ISSUE THREAD

**Issue by werleo** [aerospike/aerospike-client-ruby#41]
When do you plan to release bug fix for:
```Add node  failed: wrong number of arguments (given 3, expected 4)```
?

It is already fixed in master (2a40787a8b99c7a9607cce1c647dac7cb1ef9d6a) but there is no release with that change.
We are using aerospike-client-ruby as gem dependency so we cannot use latest version from branch.

**Comment by jhecking** [comment]
I have released v2.2.1 today, which includes this fix.
