### ISSUE TITLE
Add docs and example of how to use TLS

### ISSUE THREAD

**Issue by wallin** [aerospike/aerospike-client-ruby#64]
- [x] Add section in README describing how to enable TLS
- [ ] Add example code snippet in `examples` folder

**Comment by jhecking** [comment]
I've already added some info on how to enable TLS here: https://www.aerospike.com/docs/client/ruby/usage/connect/. But feel free to update the docs in the repo as well.

**Comment by wallin** [comment]
@jhecking Thanks for adding the examples. I like the `tls` option, it's more clean and accurate.

I'm not sure we need actual code examples since it's pretty clear how to enable it through using the policy. So closing this issue
