### ISSUE TITLE
Predicate Filtering

### ISSUE THREAD

**Issue by dorijan** [aerospike/aerospike-client-ruby#78]
Hi,
since ruby client does not support AGGREGATE query, and, it seems it will not in some time, it is necessary to implement Predicate Filtering so you could filter with more than one index
https://www.aerospike.com/docs/guide/predicate.html

Thank you
Dorijan

**Comment by jhecking** [comment]
If you are blocked by this, would you be willing to consider taking a stab at implementing predicate filtering support and submitting a pull request? I could give you some pointers to get you started.

**Comment by lijeeshsd** [comment]
Yes, I really need this, so I am interested.

**Comment by jhecking** [comment]
The Aerospike Ruby client is largely modeled after the Java client, so that would be the best reference: https://github.com/aerospike/aerospike-client-java/commit/b6355f5cb59626d422e0e36f9d622b097fe08e7d

**Comment by dorijan** [comment]
I am trying to understand, does Predicate expression filter uses same query method but predex is defined before execution? I mean this one
_https://github.com/aerospike/aerospike-client-ruby/blob/master/lib/aerospike/query/query_command.rb_

Or do we need to implement something like where and then predex filter would go as argument?

**Comment by jhecking** [comment]
The interface for using predicate expressions would look something like this:

```ruby
require 'aerospike'
include Aerospike
client = Client.new()

stmt = Statement.new("namespace", "set")
stmt.filters << Filter.Equal('bin1', 'foo')
stmt.predexp = [
  PredExp.stringBin('bin2'),
  PredExp.stringValue('bar'),
  PredExp.stringEqual(),
  PredExp.integerBin('bin3'),
  PredExp.integerValue(42),
  PredExp.integerGreater(),
  PredExp.and(2)
]

rs = client.query(stmt)
rs.each do |rec|
  puts rec
end
```

This example executes a query that uses the secondary index on "bin1" to find all records where "bin1" equals "foo". It then further narrows down the results to only return records that match the predicate expression "(bin2 == 'bar') && (bin3 > 42)". You use the same `Client#query` method to execute the query.

To implement this, you would have to create a new `PredExp` module/class, which is the public interface used to construct a predicate expression. You would also have to extend `QueryCommand#write_buffer` to serialize the predicate expression into the command buffer that's sent to the server.

The Java client code can be used as reference for both the pieces.
