### ISSUE TITLE
Encoding error (undefined conversion error) while reading digests.

### ISSUE THREAD

**Issue by apurvamayank** [aerospike/aerospike-client-ruby#84]
When I try to get the bins of a set which contains an array of digest of another set, it throws me an encoding error. Following is an example:

```
require "aerospike"

@client = Aerospike::Client.new('127.0.0.1:3000')

key_1 = Aerospike::Key.new('NS1', 'names', "123")

record = { 'name' => "Apurva Mayank" }

@client.put(key_1, record)

digest = Aerospike::BytesValue.new(key_1.digest)

key_2 = Aerospike::Key.new('NS1', 'city', "456")

record = { 'city' => "pune", "names" => [digest] }

@client.put(key_2, record)

@client.get(key_2)
```
The last line in the above code snippet throws **Encoding::UndefinedConversionError ("\x9E" from ASCII-8BIT to UTF-8)** error.

**force_encoding** in **normalize_elem** method in **unpacker.rb** seems one solution to it. I am trying to find if there is any other way to it as well.

**Comment by jhecking** [comment]
@apurvamayank, thanks for reporting this issue. In the Ruby client, binary data and strings are both  Ruby strings. But binary data uses ASCII-8BIT encoding and we should not try to change the encoding of such binary strings. Please help to check if the fix in #85 solves your problem.
