### ISSUE TITLE
Rack awareness

### ISSUE THREAD

**Issue by madejejej** [aerospike/aerospike-client-ruby#86]
Hi!

We noticed that the Ruby client doesn't implement rack awareness. We'd love to use that feature, so my question would be - is this something down in your pipeline? 

If not, would you consider accepting a PR for it?

**Comment by jhecking** [comment]
A PR would be very welcome!

**Comment by madejejej** [comment]
Hey @jhecking, I noticed the Ruby client doesn't support `Policy.replica` (https://www.aerospike.com/docs/guide/policies.html#replica) which is a prerequisite for rack awareness. Is this something you'll be adding in the near future? 

I don't think I'll have enough time to tackle both `Policy.replica` and rack awareness as these two changes together are quite extensive.

**Comment by jhecking** [comment]
No, I wasn't planning on adding support for the `replica` policy any time soon. But I'll take a look at it to get a better sense of the effort required myself. Note that I'm on leave next week, so this would likely be something I could get to the week after at the earliest.

I assume you are not using [Strong Consistency (SC) mode](https://www.aerospike.com/docs/architecture/consistency.html), right?

**Comment by madejejej** [comment]
We're not using the SC mode. Rack awareness was suggested to us by one of Aerospike's customer support people as an AWS best practice. It'd be a nice to have feature for us.

**Comment by jhecking** [comment]
Started some [initial work](https://github.com/aerospike/aerospike-client-ruby/tree/f-replicas-all) on supporting the `replicas-all` info command during the tend process, which is required to support the `replica` policy. Do expect the progress to be slow, though, since I only have few hours a week to spare on this project. And as I mentioned I will be out next week.

**Comment by madejejej** [comment]
I understand that, thanks for all the support @jhecking!

**Comment by khaf** [comment]
This has been released in the latest Ruby client a few weeks ago. I'll close this ticket, but feel free to open new tickets or reopen the issue.
