### ISSUE TITLE
Query operations ?

### ISSUE THREAD

**Issue by letronje** [aerospike/aerospike-client-ruby#9]
The official clients for python, php, etc have query support. Hope the ruby driver gets some love too :)

**Comment by zerebral** [comment]
Can we have an example for the Query operation please?  We tried the following and get "Index Error" - however the same index queries are working okay with the Node client.

```
stmt = Statement.new("dummy_namespace", "dummy_set", ["bin1", "bin2", "bin3"])
stmt.filters << Filter.Equal("bin10", query_value)
rs = client.query(stmt)
listings = []
rs.each do | rec |
    listings << rec.bins
end
```

**Comment by jhecking** [comment]
@zerebral, I have added an example for using Query operations in [examples/query.rb]( https://github.com/aerospike/aerospike-client-ruby/blob/master/examples/query.rb). Your usage looks correct, though. This is a fairly old issue that was closed a long time ago. Can you give us more details about the "Index Error" you get and how you create the secondary index in our [Community Forums](https://discuss.aerospike.com/c/client-libraries/ruby-client)?

**Comment by zerebral** [comment]
Sure.. Putting this one up on the forum. Thanks.
